### ISSUE TITLE
Compatibility with CKAN 2.8

### ISSUE THREAD

**Issue by frafra** [geosolutions-it/ckanext-geonode#5]
Hi,
I am using CKAN 2.8. I tried to load the plugin "geonode", but CKAN does not find it, so I wonder if this plugin is compatible with newer version of CKAN.

**Comment by simboss** [comment]
No Idea.

This plugin has not been used in a while.

**Comment by sebastian-bechtold** [comment]
Hello!
I have successfully installed this extension in an instance of the latest CKAN version 2.8.3. At least, it *looks* good. No error messages during the installation process, and the expected GUI elements are there.

However, when I try to harvest a GeoNode instance, the process fails with some error with no further explanation. All that happens is that a box with the content "An error occurred: []" shows up in the CKAN UI.

Any ideas what might be wrong?

**Comment by frafra** [comment]
@sebastian-bechtold I still did not solve that, but I need to do it. It seems to me that there is a problem with the schema being used, that expects some XML fields in a different order.
**Edit**: that issue is related to ckanext-spatial, not ckanext-geonode

**Comment by sebastian-bechtold** [comment]
@frafra:
So this is something that is still being worked on? This is good to know. 

I'm currently working on an alternative stand-alone GeoNode-to-CKAN harvest script (in Python) which accesses GeoNode through its JSON API. For now, this is a very, very simple thing and not generic enough for general use without modifications. But if I can help you with something, let me know. I know nothing about CKAN extension development (yet), though.

**Comment by frafra** [comment]
@sebastian-bechtold yes, this is something I need at work.

I made various wrapper around different sources in order to harvest them with CKAN and the same could be done for GeoNode too. I would be happy to cooperate on such kind of project.

**Comment by frafra** [comment]
@sebastian-bechtold alternative: ckanext-spatial; see https://github.com/ckan/ckanext-spatial/issues/223

**Comment by etj** [comment]
@frafra @sebastian-bechtold this plugin was only working with really old CKAN version.
It has always used the geonode APIs.

There's no plan to make this extension work with CKAN2.8, but new commits have just been done in order to make this extension compatible with python3 and CKAN2.9. 

I'm going to close this issue.
